set(LOCALIZATION_PLUGIN_NAME HobbyPlugin_Localization)
set(LOCALIZATION_PLUGIN_INC_DIR ${CMAKE_CURRENT_LIST_DIR}/Inc)

set(LOCALIZATION_PLUGIN_TARGET_COMMON_FILES
    .editorconfig
    LICENSE.txt
    README.md
)

set(LOCALIZATION_PLUGIN_TARGET_INC_FILES
    Inc/LocalizationModule.h
)

set(LOCALIZATION_PLUGIN_TARGET_SRC_FILES
    Src/LocalizationModule.cpp
)
